name: deploy
on:
    push:
        branches:
            - master
    repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        for i in {1..5}; do curl -L -H "Authorization: token  ${{ secrets.ACCESS_TOKEN }}" -o ./scripts/releases.json https://api.github.com/repos/realoptions/option_price_faas/releases/latest && break || sleep 10; done 
        tag=$(node ./scripts/outputTag)
        echo "REACT_APP_TAG=$tag" >> .env
        echo "this is the tag #: $tag"
        echo "REACT_APP_FirebaseAPIKey=${{ secrets.FIREBASE_API_KEY }}" >> .env
        npm ci
        access_token=${{ secrets.ACCESS_TOKEN }} node ./scripts/downloadYML.js
        rm -r node_modules
        NODE_ENV=production npm ci
        npm run build
      env:
        CI: True
        
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with: 
        # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: build