name: deploy
on:
    push:
        branches:
            - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        echo "REACT_APP_FirebaseAPIKey=${{ secrets.FIREBASE_API_KEY }}" >> .env
        npm ci
        npm run build
      env:
        CI: True
        
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@master
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build