name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "23.5.0"
      - name: test build
        run: |
          npm ci
          npm run build
        env:
          CI: true
